Add timeout to py-spy run
Granulate/gprofiler pull request #149
Opened 2021-07-26 07:41 UTC by Jongy

# Description
Adds timeouts to `run_process()` and use them when running py-spy, because we've seen py-spy hanging already.

Later on we can add timeouts to other executions of processes in gProfiler.

## Motivation and Context
Prevent py-spy hangs from hanging gProfiler entirely.

## How Has This Been Tested?
I changed `timeout=self._duration + self._EXTRA_TIMEOUT` to `timeout=self._duration - self._EXTRA_TIMEOUT` and all py-spys failed with proper error.

The CI will test the usual case of no timeout.

## Checklist:
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated the relevant documentation.
- [ ] I have added tests for new logic.

2021-07-26 07:47 UTC, michelhe requested changes
.

2021-07-26 07:47 UTC, michelhe commented on gprofiler/utils.py
> +                        if end_time is not None and time.monotonic() > end_time:
Why would 'end_time' be none here?

2021-07-26 07:47 UTC, michelhe commented on gprofiler/utils.py
>                          stdout, stderr = process.communicate(timeout=1)
timeout=timeout ?

2021-07-26 07:54 UTC, Jongy commented on gprofiler/utils.py
> +                        if end_time is not None and time.monotonic() > end_time:
If I didn't pass `timeout`

2021-07-26 07:56 UTC, michelhe approved these changes

2021-07-26 10:28 UTC, Jongy commented
> http://vault.centos.org/centos/6/os/x86_64/Packages/rsync-3.0.6-12.el6.x86_64.rpm: [Errno 14] PYCURL ERROR 7 - "Failed to connect to 2600:1f16:c1:5e03:a992:8ee1:99d2:6f8: Cannot assign requested address"

pfft

2021-07-29 11:26 UTC, michelhe approved these changes

2021-07-29 11:33 UTC, merged