Python: Make packages info representation more distinguishable
Granulate/gprofiler pull request #251
Opened 2021-12-27 11:25 UTC by YishaiZinkin

## Description

Surround module info in stacks with `[]` instead of `()` and separate the package name from the package version with `:` instead of `-`.

For example, this symbol:
`scapy.utils.PcapReader.read_packet (/usr/lib/python3.6/site-packages/scapy/utils.py:1347 (scapy-2.4.5))_[p]`
Will be now presented like this:
`scapy.utils.PcapReader.read_packet (/usr/lib/python3.6/site-packages/scapy/utils.py:1347 [scapy==2.4.5])_[p]`

## Motivation and Context
* Regular parenthesis are already used to separate the metadata section of the symbol, so using another kind of parenthesis for the package info is more noticeable and easier to read.
* The character `"-"` can be part of a package name or version, so it's better to use characters that can't appear in either of them.

## How Has This Been Tested?

## Screenshots

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have updated the relevant documentation.
- [ ] I have added tests for new logic.

2021-12-27 11:42 UTC, Jongy approved these changes
LGTM. @guybortnikov please approve as well.

2021-12-30 13:14 UTC, Jongy commented
@guybortnikov bump

2021-12-30 14:15 UTC, guybortnikov requested changes
@YishaiZinkin looks good, please fix tests and I'll approve

2021-12-30 14:20 UTC, Jongy commented
Failures seem irrelevant. If your test passes, it'k k

2022-01-03 14:22 UTC, guybortnikov approved these changes

2022-01-03 14:23 UTC, merged