java: async-profiler: Set default mode to "cpu"
Granulate/gprofiler pull request #267
Opened 2022-01-13 16:41 UTC by Jongy

## Description
It's time :)

We now trust the CPU mode enough to set it by default.

## How Has This Been Tested?
CI, and in some of our deployments.

2022-01-13 16:56 UTC, liorgorb submitted a review, later dismissed

2022-01-13 23:41 UTC, Jongy commented
@liorgorb ready for CR

2022-01-15 17:41 UTC, Jongy commented
Now it's passing... How nice

2022-01-26 13:32 UTC, adi-benz requested changes
I can't really comment on the core essence of this PR, I don't have a good understanding on the differences between `itimer` and `cpu` (other than docs and a little bit of code reading), and I don't know what's the problems `cpu` had in the past that now we trust it.

So as far as reviewing the simple code that chooses the mode - no problem  
But I don't have any meaningful comments about `cpu` mode vs `itimer`, so maybe we want someone that knows it to take a look?

2022-01-26 13:42 UTC, Jongy commented
> I can't really comment on the core essence of this PR, I don't have a good understanding on the differences between itimer and cpu (other than docs and a little bit of code reading), and I don't know what's the problems cpu had in the past that now we trust it.

Generally: CPU is based on `perf_events` which we have concluded to be more accurate than `itimer`, so we want it to be used when available.

We use CPU mode with `fdtransfer` which is a mechanism that [I've added to async-profiler](https://github.com/jvm-profiling-tools/async-profiler/pull/411) a while ago. It was a new feature in AP and we wanted to have some "run time" before we enable it by default. We've had a while with it and now we deem it ready.

2022-01-26 13:52 UTC, Jongy commented on tests/utils.py
> +    print(logs)  # will be displayed if the test fails
pytest doesn't show the stdout of passing tests, only upon failure, so it's a common pattern

2022-01-26 15:50 UTC, Jongy commented on gprofiler/utils.py
> +def perf_path() -> str:
Well, we have `perf.py` for the profiler but it doesn't belong there now I suppose. Time to create a utils directory... And slowly slowly split up this large file.

2022-01-26 15:53 UTC, Jongy commented
> But I don't have any meaningful comments about cpu mode vs itimer, so maybe we want someone that knows it to take a look?

Was approved by @liorgorb and @YoniKF as well.

2022-01-26 16:19 UTC, adi-benz commented on tests/utils.py
> +    print(logs)  # will be displayed if the test fails
Running pytest with `-s` makes it show stdout, which in my experience is quite useful for debugging and such.  
Also, PyCharm shows stdout by default when clicking on each test.

I don't see any downsides to printing the logs using the assert, it's also simpler (you won't feel the need to document `# will be displayed if the test fails` on an assert)

2022-01-26 16:19 UTC, adi-benz commented
> > But I don't have any meaningful comments about cpu mode vs itimer, so maybe we want someone that knows it to take a look?
> 
> Was approved by @liorgorb and @YoniKF as well.

Cool 👍

2022-01-26 16:20 UTC, Jongy commented on tests/utils.py
> +    print(logs)  # will be displayed if the test fails
> Running pytest with -s makes it show stdout, which in my experience is quite useful for debugging and such.
Also, PyCharm shows stdout by default when clicking on each test.

Hmm weird. I'm using `pytest -s` by default but I see the outputs only upon failure.

Will move to the assert, k

2022-01-26 16:30 UTC, adi-benz commented on tests/utils.py
> +    print(logs)  # will be displayed if the test fails
I tested it to make sure

![image](https://user-images.githubusercontent.com/73543893/151204797-06d6826c-e244-40e2-8315-9436e357616f.png)

2022-01-26 16:30 UTC, adi-benz approved these changes

2022-01-26 16:54 UTC, merged