appids: Show the original identifier (per the user) as well as the normalized one
Granulate/gprofiler pull request #289
Opened 2022-02-07 17:29 UTC by Jongy

## Description
For better user experience - show the "identifier" as the user has written it, in addition to showing the normalized one.

TODOs:
* [ ] uwsgi appid tests
* [ ] uwsgi `--ini-paste` support

2022-02-08 10:23 UTC, guybortnikov commented on gprofiler/metadata/application_identifiers.py
> +    return resolve_proc_root_links(f"/proc/{process.pid}/root", file_path)
Strip proc_root

2022-02-08 10:24 UTC, guybortnikov requested changes
.

2022-02-08 19:24 UTC, Jongy commented
@guybortnikov GH is retarded and doesn't display the diff of the tests file properly, use this instead: `git diff master:tests/test_appid.py origin/appid-improvements:tests/test_appids.py` (after `gill pull`)

2022-02-09 08:51 UTC, guybortnikov commented on gprofiler/metadata/application_identifiers.py
> +        config.read_file(cls._open_uwsgi_config_file(process, config_file))
Close the file in `finally` block (or either use some contextmanager on your `_open_uwsgi_config_file`) 
I know you're gonna tell me GC will clean it but it's a bad practice.

2022-02-09 08:52 UTC, guybortnikov requested changes
Looks good, small comment

2022-02-09 09:28 UTC, guybortnikov approved these changes

2022-02-09 10:10 UTC, merged