ProfileData API
Granulate/gprofiler pull request #326
Opened 2022-03-29 08:27 UTC by Jongy

## Description
This PR introduces a new API between the runtime profilers and gprofiler core: `ProfileData`.

APIs are not finalized yet.:
* [ ] I don't like the current mess in `merge.py`
* [ ] If appids / metadata are disabled, then we need to prevent gprofiler from trying to retrieve them (not just from adding them; with this PR, we still collect them despite not adding)

The idea is to use a more rich output format for profilers - not just PID -> stackcollapse, but PID -> object with numerous fields, one of them being stackcollapse.

Currently, the 2 additional fields are the appid and app metadata. Logically, it makes sense that the runtime profilers retrieve them, and not the generic area in gprofiler - because these are per-runtime anyway. Code is structured more "sensibly" when runtime profilers return these values.

Also, it serves a technical purpose: if profilers collect & attach the appid & app metadata directly to the profile data, we can be sure that:
* App id & metadata are always collected consistently - if a certain app has "appid: X", then all stacks of it will have that appid. Previously it wasn't the case, because we could profile a process that'd go down before we had the chance to get its app id (was retrieved post profiling).
* No chance for PID reuse collision - PID being reused by another app and we get the wrong data.

That's ^^ not true yet for pyperf, because pyperf still attaches this data post profiling. This will change in a PR after https://github.com/Granulate/gprofiler/pull/281 - where we will move the process selection to gprofiler from pyperf, and then gprofiler will take the metadata & id of apps before pyperf begins to profile them.

## How Has This Been Tested?
CI

2022-03-30 07:53 UTC, adi-benz reviewed
Looks great, and not such a big change LOC-wise

2022-04-10 15:19 UTC, adi-benz requested changes

2022-04-10 16:28 UTC, Jongy commented on gprofiler/gprofiler_types.py
> +    appid: Optional[str]
Hmm also true, but let's not continue enlarging this PR, I'll do as a separate PR?

2022-04-10 16:28 UTC, Jongy commented on gprofiler/metadata/application_identifiers.py
> +    def get_app_id(self, process: Process) -> Optional[str]:
Yup

2022-04-10 16:29 UTC, Jongy commented on tests/conftest.py
>  def assert_application_name(application_pid: int, runtime: str, in_container: bool) -> Generator:
Fixed

2022-04-10 16:29 UTC, Jongy commented on tests/utils.py
> +def snapshot_pid_collaped(profiler: ProfilerInterface, pid: int) -> StackToSampleCount:
Was fixed (refresh your view?)

2022-04-10 16:29 UTC, Jongy commented on tests/utils.py
> +def snapshot_pid_collaped(profiler: ProfilerInterface, pid: int) -> StackToSampleCount:
Or not. wtf

2022-04-10 16:36 UTC, Jongy commented on gprofiler/merge.py
> +            perf_samples_count = 0
`scale_sample_counts` won't write stacks that have 0 samples, so it actually ends up returning an empty `Counter`

2022-04-17 15:50 UTC, adi-benz submitted a review, later dismissed

2022-04-17 16:09 UTC, adi-benz approved these changes

2022-04-17 16:59 UTC, merged