Upgrade granulate-utils and add a test for resolve_proc_root_links()
Granulate/gprofiler pull request #338
Opened 2022-04-11 12:03 UTC by Jongy

Upgrade granulate-utils, this includes 2 new commits:
1. Some changes to `resolve_proc_root_links()` - we didn't have a test that triggers the underlying logic in this function, so I hacked one now that tests it to full extent. CC @ty93 
2. `elf.py` moved to granulate-utils, use the copy from there.

2022-04-13 17:05 UTC, Jongy commented
Forgot to mention - I ran the new test with the old code (not the updated granulate-utils) and obv it fails.

2022-04-17 12:16 UTC, adi-benz requested changes

2022-04-17 12:16 UTC, adi-benz commented on tests/test_java.py
> +    # /run/tmp -> /run/step1
`/run/tmpy`

2022-04-17 12:16 UTC, adi-benz commented on tests/test_java.py
> +            "ln -s final_tmp /run/step2 && "
```suggestion
            "ln -s final_tmp /run/step2 && "  # Test relative path
```

2022-04-17 12:16 UTC, adi-benz commented on tests/test_java.py
> +            "ln -s /run/step1 /run/tmpy && "
```suggestion
            "ln -s /run/step1 /run/tmpy && "  # Test absolute path
```

2022-04-17 12:43 UTC, adi-benz approved these changes

2022-04-17 12:47 UTC, merged