java: parse_jvm_version(): Handle single-digit builder number suffix
Granulate/gprofiler pull request #376
Opened 2022-06-13 17:19 UTC by Jongy

For example - "1.8.0_292-b2"

2022-06-13 19:35 UTC, Jongy commented
I'll re-run the query within a few days to get more unique samples, and if it passes, we'll merge.

2022-06-19 17:54 UTC, Jongy commented
> I'll re-run the query within a few days to get more unique samples, and if it passes, we'll merge.

I re-ran, it's okay

2022-06-21 13:34 UTC, michelhe requested changes
.

2022-06-21 13:34 UTC, michelhe commented on gprofiler/profilers/java.py
> +    if version_str.endswith("-internal") or version_str.endswith("-ea") or version_str.endswith("-ojdkbuild"):
```suggestion
    if any(version_str.endswith(suffix) for suffix in ("-internal", "-ea", "-ojdkbuild")):
```

2022-06-23 11:58 UTC, michelhe approved these changes

2022-07-14 00:13 UTC, merged