Enable phpspy for Aarch64
Granulate/gprofiler pull request #430
Opened 2022-08-06 22:43 UTC by Jongy

phpspy test results (on our branch):
```
TEST tests/test_varpeek.sh
process_vm_readv: No such process
  OK   varpeek
process_vm_readv: No such process
  OK   varpeek

TEST tests/test_pgrep_time_limit.sh
main_pgrep finished gracefully
  ERR  frame_1
expected=^1 <main> <internal>:-1$

actual=

TEST tests/test_pgrep_trace_limit.sh
main_pgrep finished gracefully
  ERR  exit_code=124

TEST tests/test_time_limit.sh
  OK   include_sleep

TEST tests/test_child.sh
  OK   req_uri
  ERR  req_ts
expected=^# ts = \d+\.\d+$

actual=
0 usleep <internal>:-1
1 <main> <internal>:-1
# uri = -
# path = Standard input code
# qstring = -
# cookie = -
# ts = -nan

TEST tests/test_verbose.sh
  OK   verbose_pid
  OK   frame_1
  OK   verbose_ts
  OK   frame_0

TEST tests/test_mem.sh   
  SKIP alloc_globals symbol not found

TEST tests/test_flamegraph.sh
  OK   flamegraph

TEST tests/test_filter.sh
process_vm_readv: No such process
  OK   include_nanosleep
  OK   exclude_usleep
process_vm_readv: No such process
  OK   negate_include_nanosleep
  OK   negate_exclude_usleep

TEST tests/test_glopeek.sh
process_vm_readv: No such process
  OK   glopeek_server_new
  OK   glopeek_server_mod
  OK   glopeek_globals
  OK   glopeek_server
process_vm_readv: No such process
  OK   glopeek1
  OK   glopeek2

TEST tests/test_varpeek_range.sh
process_vm_readv: No such process
  OK   varpeek_range_a_3
  OK   varpeek_range_a_1
  OK   varpeek_range_b_4
  OK   varpeek_range_b_2

TEST tests/test_pid.sh
  OK   frame_1
  OK   frame_0

TEST tests/test_pgrep.sh
main_pgrep finished gracefully
  ERR  frame_1
expected=^1 <main> <internal>:-1$

actual=

TEST tests/test_buffer_full.sh
event_handler_fout_snprintf: Not enough space in buffer; truncating
  OK   frame_0
  OK   no_frame_1
event_handler_fout_snprintf: Not enough space in buffer; truncating
  OK   nothing

Passed 10 out of 14 tests
```

Not all pass but it's enough to try this experimental support.

Resolves: https://github.com/Granulate/gprofiler/issues/429

2022-08-06 22:59 UTC, Jongy commented
I tested the exe & container build on aarch64 - both pass. Since php is not enabled by default and is considered experimental, this is good enough to merge IMO.

2022-08-06 23:37 UTC, Jongy commented
Unrelated failure (the py 3.6 bug)

2022-08-07 08:24 UTC, michelhe requested changes
LGTM, lets add a note that phpspy aarch64 is experimental in our readme

2022-08-07 12:46 UTC, michelhe approved these changes

2022-08-07 12:58 UTC, merged