Allow disabling runtime-specific profilers
Granulate/gprofiler pull request #55
Opened 2021-05-02 00:01 UTC by Jongy

## Description
Allow disabling the runtime-specific profilers via `--no-java` and `--no-python`.

Since there are only 2 runtime-specific profilers now, I didn't invest too much in the "NoopProfiler" infrastructure. Later on we can replace those sets of funny `if`s with a proper class registry for profilers (profilers can be `@register("java")` and then we can decide if we use the registered class or `NoopProfiler` at 1 spot)

## Motivation and Context
Give more control to the user. It might be useful to disable runtime-specific profilers in case either of them cause issues / compatibility problems. If need the results only from part of them, disabling the others (especially as we grow to add more profilers) might be helpful in such cases.

## How Has This Been Tested?
Tested running locally with the 4 combinations of `--no-java`, `--no-python` and verified that Java/Python profilers are not initialized when not requested.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have updated the relevant documentation.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-05-02 00:42 UTC, Jongy commented
Build failure is fixed in https://github.com/Granulate/gprofiler/pull/56

2021-05-06 12:54 UTC, leonid-granulate requested changes
I saw your comment about an `if` statements and replacement by decorators, maybe it worth to create an issue.

2021-05-06 12:54 UTC, leonid-granulate commented on gprofiler/java.py
> +    def _run_async_profiler(self, cmd: str, log_path_host: str):
```suggestion
    def _run_async_profiler(self, cmd: Union[str, List[str]], log_path_host: str):
```

2021-05-06 15:59 UTC, Jongy commented on gprofiler/java.py
> +    def _run_async_profiler(self, cmd: str, log_path_host: str):
Just `List[str]` will do

2021-05-08 18:14 UTC, leonid-granulate approved these changes

2021-05-09 06:58 UTC, merged

2021-05-09 06:58 UTC, Jongy commented
> I saw your comment about an `if` statements and replacement by decorators, maybe it worth to create an issue.

Will do