Enable running gprofiler executable on Alpine
Granulate/gprofiler pull request #701
Opened 2023-02-23 11:47 UTC by mpozniak95

## Description
Alpine grep doesn't support flag -P (Perl compatible regular expressions), so pgrep_map method now uses -E (Extended regular expressions)

## Related Issue
https://github.com/Granulate/gprofiler/issues/636

2023-02-23 12:57 UTC, mpozniak95 commented on gprofiler/profilers/python.py
> +                x for x in pgrep_maps(r"(^.+/(lib)?python[^/]*$)|(^.+/site-packages/.+?$)|(^.+/dist-packages/.+?$)")
Wasn't sure that if I change it in granulate-utils if this won't change something in other repository.

2023-02-23 13:03 UTC, mpozniak95 commented on gprofiler/profilers/python.py
> +                x for x in pgrep_maps(r"(^.+/(lib)?python[^/]*$)|(^.+/site-packages/.+?$)|(^.+/dist-packages/.+?$)")
Added PR in granulate-utils: https://github.com/Granulate/granulate-utils/pull/124

2023-02-23 13:08 UTC, Jongy commented on gprofiler/profilers/python.py
> +                x for x in pgrep_maps(r"(^.+/(lib)?python[^/]*$)|(^.+/site-packages/.+?$)|(^.+/dist-packages/.+?$)")
Any other pattern we should fix?

2023-02-23 13:38 UTC, mpozniak95 commented on gprofiler/profilers/python.py
> +                x for x in pgrep_maps(r"(^.+/(lib)?python[^/]*$)|(^.+/site-packages/.+?$)|(^.+/dist-packages/.+?$)")
We use pgrep_maps in four places in code, I changed three patterns and java pattern works with grep -E flag too

2023-02-23 19:54 UTC, Jongy commented on gprofiler/profilers/python.py
> +                x for x in pgrep_maps(r"(^.+/(lib)?python[^/]*$)|(^.+/site-packages/.+?$)|(^.+/dist-packages/.+?$)")
Gotcha

2023-02-23 19:55 UTC, Jongy commented on gprofiler/profilers/python.py
> +                x for x in pgrep_maps(r"(^.+/(lib)?python[^/]*$)|(^.+/site-packages/.+?$)|(^.+/dist-packages/.+?$)")
I merged - so update the granulate-utils reference to https://github.com/Granulate/granulate-utils/commit/cb66a9fe803d0448ac6eea6aceb85e34a88b0b8f, and revert this change

2023-02-23 19:56 UTC, Jongy commented on gprofiler/utils/__init__.py
> +        f"grep -lE '{match}' /proc/*/maps",
You can comment here explaining about the choice of `-E` over `-P` (to support systems where grep is not PCRE)

2023-02-23 19:56 UTC, Jongy requested changes
Final comments

2023-02-24 17:11 UTC, Jongy approved these changes

2023-02-24 17:11 UTC, Jongy commented
Good job :)

2023-02-24 17:12 UTC, merged