gunicorn appid improvement
Granulate/gprofiler pull request #816
Opened 2023-06-27 11:59 UTC by pfilipko1

Works properly, not sure about the naming convention though.
https://github.com/Granulate/gprofiler/issues/704

2023-06-27 12:59 UTC, Jongy requested changes
Before I begin reviewing, can you please add tests next to `test_gunicorn` in `test_appids.py`? (tests that show this change now supports the cases described in the ticket)

2023-06-27 13:44 UTC, pfilipko1 commented
Added two test cases (hopefully correct) containing commands with multiple arguments containing ":"

2023-07-02 07:38 UTC, Jongy commented on gprofiler/metadata/application_identifiers.py
> +        # wsgi app specification must not be the last argument, thus the method to extract it
```suggestion
        # wsgi app specification might not be the last argument, thus the method to extract it
```

2023-07-02 07:42 UTC, Jongy commented on gprofiler/metadata/application_identifiers.py
> +                    return arg
Why do you require `cmdline_colon_list`? Can't you replace `arg == colon_arg` with `":" in arg`?

2023-07-02 07:43 UTC, Jongy commented on tests/test_appids.py
Let's add one test case for the negative case, i.e for `return "unknown app name"`.

2023-07-02 07:43 UTC, Jongy requested changes
.

2023-07-05 17:50 UTC, Jongy approved these changes

2023-07-05 17:51 UTC, merged