bugfix: `start_process` ensuring passing of `TMPDIR` when needed
Granulate/gprofiler pull request #922
Opened 2024-09-11 06:56 UTC by roi-granulate

## Description
https://github.com/Granulate/gprofiler/pull/921#discussion_r1743316860

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have updated the relevant documentation.
- [ ] I have added tests for new logic.

2024-09-11 06:57 UTC, roi-granulate commented on gprofiler/utils/__init__.py
>              env = env if env is not None else os.environ.copy()
```suggestion
            env = env or os.environ.copy()
```

2024-09-22 11:19 UTC, Jongy commented on gprofiler/utils/__init__.py
>              env = env if env is not None else os.environ.copy()
No, prefer explicit `is None`

2024-09-22 11:19 UTC, Jongy commented on gprofiler/utils/__init__.py
> +                env["TMPDIR"] = os.environ.get("TMPDIR")
```suggestion
                env["TMPDIR"] = os.environ["TMPDIR"]`
```
makes it clear that the value can't be `None`.

2024-09-22 11:19 UTC, Jongy requested changes
.

2024-09-22 11:34 UTC, Jongy commented on gprofiler/utils/__init__.py
>              # explicitly remove our directory from LD_LIBRARY_PATH
Move the comment to its relevant code line now. And add another comment explaining the TMPDIR ("respect the TMPDIR we were run with in all cases")

2024-09-22 11:55 UTC, Jongy submitted a review, later dismissed

2024-09-23 07:07 UTC, Jongy approved these changes

2024-09-23 08:08 UTC, merged